server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/StevenBuglione/ProjectUnknown
          search-paths: 'Apps/Config-Store/*service'
          default-label: main
